name: 'bde'
version: '1.0.0'
config-version: 2

profile: 'bde'

# Specifying where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

models:
  bde:
    +materialized: view  # Materialize models as views.
